In [1]:
import pandas as pd
import numpy as np

In [2]:
df =  pd.read_csv('purchase_history.csv')

In [3]:
df.head()

Customer ID  Gender  Age  Salary Product ID  Price  Purchased
0            1  Female   49   61000        P01   2000          1
1            2    Male   36   30000        P02   2000          1
2            3  Female   26   81000        P02   3500          1
3            4  Female   32   74000        P01   7000          0
4            5  Female   42   56000        P01   5000          0

In [4]:
df.shape

(1000, 7)

In [5]:
df.describe()

Customer ID          Age         Salary        Price    Purchased
count  1000.000000  1000.000000    1000.000000  1000.000000  1000.000000
mean    500.500000    40.989000   58667.000000  4435.500000     0.414000
std     288.819436    13.738837   23615.372044  1847.973148     0.492795
min       1.000000    18.000000   20000.000000  2000.000000     0.000000
25%     250.750000    29.000000   38000.000000  3500.000000     0.000000
50%     500.500000    40.000000   59000.000000  5000.000000     0.000000
75%     750.250000    53.000000   80000.000000  7000.000000     1.000000
max    1000.000000    64.000000  100000.000000  7000.000000     1.000000

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 7 columns):
 #   Column       Non-Null Count  Dtype 
---  ------       --------------  ----- 
 0   Customer ID  1000 non-null   int64 
 1   Gender       1000 non-null   object
 2   Age          1000 non-null   int64 
 3   Salary       1000 non-null   int64 
 4   Product ID   1000 non-null   object
 5   Price        1000 non-null   int64 
 6   Purchased    1000 non-null   int64 
dtypes: int64(5), object(2)
memory usage: 54.8+ KB


In [7]:
df.isnull().sum()

Customer ID    0
Gender         0
Age            0
Salary         0
Product ID     0
Price          0
Purchased      0
dtype: int64

In [8]:
df

Customer ID  Gender  Age  Salary Product ID  Price  Purchased
0              1  Female   49   61000        P01   2000          1
1              2    Male   36   30000        P02   2000          1
2              3  Female   26   81000        P02   3500          1
3              4  Female   32   74000        P01   7000          0
4              5  Female   42   56000        P01   5000          0
..           ...     ...  ...     ...        ...    ...        ...
995          996    Male   21   73000        P02   5000          1
996          997    Male   62   54000        P01   5000          0
997          998  Female   41   20000        P03   2000          0
998          999    Male   22   29000        P03   5000          0
999         1000  Female   49   36000        P03   3500          0

[1000 rows x 7 columns]

In [9]:
df.drop(['Customer ID', 'Product ID'], axis=1, inplace=True)

In [10]:
df

Gender  Age  Salary  Price  Purchased
0    Female   49   61000   2000          1
1      Male   36   30000   2000          1
2    Female   26   81000   3500          1
3    Female   32   74000   7000          0
4    Female   42   56000   5000          0
..      ...  ...     ...    ...        ...
995    Male   21   73000   5000          1
996    Male   62   54000   5000          0
997  Female   41   20000   2000          0
998    Male   22   29000   5000          0
999  Female   49   36000   3500          0

[1000 rows x 5 columns]

In [11]:
df.Gender = df.Gender.replace(['Male','Female'], [1,0])

In [12]:
df

Gender  Age  Salary  Price  Purchased
0         0   49   61000   2000          1
1         1   36   30000   2000          1
2         0   26   81000   3500          1
3         0   32   74000   7000          0
4         0   42   56000   5000          0
..      ...  ...     ...    ...        ...
995       1   21   73000   5000          1
996       1   62   54000   5000          0
997       0   41   20000   2000          0
998       1   22   29000   5000          0
999       0   49   36000   3500          0

[1000 rows x 5 columns]

In [13]:
x = df[['Gender', 'Age', 'Salary', 'Price']].to_numpy()

In [14]:
y = df['Purchased'].to_numpy()

In [15]:
x

array([[    0,    49, 61000,  2000],
       [    1,    36, 30000,  2000],
       [    0,    26, 81000,  3500],
       ...,
       [    0,    41, 20000,  2000],
       [    1,    22, 29000,  5000],
       [    0,    49, 36000,  3500]], dtype=int64)

In [16]:
y

array([1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1,
       0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0,
       0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0,
       1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0,
       0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1,
       0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1,
       0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1,
       0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1,
       0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0,
       1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0,

In [17]:
from sklearn.model_selection import train_test_split

In [18]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state =42)

In [19]:
x_train

array([[    1,    26, 28000,  5000],
       [    1,    54, 21000,  7000],
       [    0,    42, 22000,  5000],
       ...,
       [    0,    59, 91000,  2000],
       [    0,    31, 82000,  2000],
       [    0,    20, 34000,  5000]], dtype=int64)

In [20]:
y_train

array([0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0,
       0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0,
       1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0,
       1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1,
       1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1,
       0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1,
       1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1,
       1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1,
       0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1,
       1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0,
       0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0,
       0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0,
       1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0,

In [21]:
len(x_train)

800

In [22]:
len(x_test)

200

In [23]:
from sklearn.preprocessing import StandardScaler

In [26]:
scaler = StandardScaler()

x_train = scaler.fit_transform(x_train)
x_test = scaler.fit_transform(x_test)

In [27]:
from sklearn.neighbors import KNeighborsClassifier

In [58]:
k=7
knn = KNeighborsClassifier(n_neighbors=k)

In [59]:
knn.fit(x_train, y_train)

KNeighborsClassifier(n_neighbors=7)

In [60]:
y_pred = knn.predict(x_test)

In [61]:
y_pred

array([1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0,
       1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0,
       1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1,
       0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0,
       1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1,
       0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0,
       1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1,
       0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0,
       0, 0], dtype=int64)

In [62]:
from sklearn.metrics import accuracy_score

In [63]:
accuracy = accuracy_score(y_test, y_pred)
accuracy

0.79

In [64]:
import pickle

In [65]:
with open('knn_model.pickle', 'wb') as f:
    pickle.dump(knn, f)

In [66]:
with open('scaler.pickle', 'wb') as f:
    pickle.dump(scaler, f)

In [69]:
ls

 Volume in drive E is Money
 Volume Serial Number is 483E-CB4B

 Directory of E:\Coding\Python\Customer Aalysis

07/06/2024  06:28 PM    <DIR>          .
07/06/2024  06:28 PM    <DIR>          ..
07/06/2024  04:29 PM    <DIR>          .ipynb_checkpoints
07/06/2024  06:28 PM            42,501 knn_model.pickle
10/03/2019  02:10 PM             3,981 Mall_Customers.csv
07/04/2024  11:35 PM           135,781 MallCustomers.ipynb
07/06/2024  04:28 PM               251 new_customers.csv
07/06/2024  04:28 PM            30,007 purchase_history.csv
07/06/2024  06:28 PM            57,171 PurchaseBehaviour.ipynb
07/06/2024  06:28 PM               551 scaler.pickle
               7 File(s)        270,243 bytes
               3 Dir(s)  17,003,642,880 bytes free
